Resources:

  notesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: notes-${self:provider.stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: notesId
          AttributeType: S
      KeySchema:
        - AttributeName: notesId
          KeyType: HASH

  cognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: KennyRodgers-${self:provider.stage}

  cognitoUserPoolWebclient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref cognitoUserPool
      ClientName: web
      AllowedOAuthFlowsUserPoolClient: true
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthScopes:
        - phone
        - email
        - profile
        - openid
      AllowedOAuthFlows:
        - implicit
      CallbackURLs:
        - http://localhost:3000

  cognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref cognitoUserPool
      Domain: kennyrodgers-${self:provider.stage}

  userPoolArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /notes/${self:provider.stage}/userPoolArn
      Type: String
      Value: !GetAtt cognitoUserPool.Arn
